package com.android.fitnessapplication;

public class ListOfWorkouts {
    static String[][] listOfWorkouts = {
            { "Explosive Chest",    //workout name
                "Chest",    // filter
                "3",        //# sets
                "Barbell Bench Press", "6-8", //this point down are the exercise name and reps
                "Dumbbell Bench Press", "10-12",
                "Chest Flies", "10-12",
                "Cable Flies", "10-12",
                "Chest Press", "10-12",
                "Incline Bench Press", "6-8",
                "Dips", "6-8",
                "Push-Ups", "15-20" },
            { "Pumped Up ShoulderS",
                "Shoulders",
                "3",
                "Military Press", "4-6",
                "Push Press", "AMRAP",
                "Dumbell Shoulder Press", "8-10",
                "Lateral Raises", "12-15",
                "Shrugs", "20",
                "Cable Extensions", "12",
                "Rear Delt Flies", "10-12",
                "Farmers Carry", "30 seconds"
            },
            { "Blasting Biceps",
                    "Biceps",
                    "4",
                    "Dumbbell Curl", "12 Each Arm",
                    "Hammer Curl", "12 Each Arm",
                    "Preacher Curl", "12",
                    "Barbell Strict Curl", "8",
                    "Chin-Ups", "AMRAPS",
                    "Concentration Curl", "12 Each Arm"
            },
            { "Tearing-Up Triceps",
                    "Triceps",
                    "4",
                    "Tricep Pushdown", "12",
                    "Overhead Tricep Extension", "15",
                    "Tricep Dumbbell Kickback", "8",
                    "Dips", "AMRAPS",
                    "Skullcrushers", "10",
                    "Push-Ups", "12"
            },
            { "Killer Core",
                    "Abs & Obliques",
                    "3",
                    "Sit-Ups", "12",
                    "Crunches", "20",
                    "Planks", "1 Minute",
                    "Hanging Leg Raises", "12",
                    "Superman", "10",
                    "Lumberjack Swings", "12 Each Side",
                    "Russian Twist", "20" },
            { "Light-Em-Up Legs",
                    "Legs",
                    "3",
                    "Back Squat", "8",
                    "Front Squat", "8",
                    "Leg Extensions", "12",
                    "Calf Raises", "20",
                    "Leg Press", "12",
                    "Romanian Deadlift", "10",
                    "Lunges", "25",
                    "Leg Curls", "12" },
            { "Bursting Back",
                    "Back",
                    "4",
                    "Barbell Deadlift", "6",
                    "Cleans", "4",
                    "Lat PUlldown", "10-12",
                    "Barbell Rows", "8",
                    "Cable Rows", "12",
                    "Pull-Ups", "AMRAPS",
                    "T-bar Rows", "10" },
            { "Greedy Glutes",
                    "Glutes",
                    "3",
                    "Hip Thrusts", "8",
                    "Back Squat", "6",
                    "Trap-Bar Deadlift", "6",
                    "Kettlebell Swing", "12",
                    "Bulgarian Split Squat", "8",
                    "Good Morning", "6",
                    "Cable Kickback", "12" }
    };

    static String[] exercises = {
            "Push Down",
            "Push Up",
            "Pull Far Down",
            "Push Far Up",
            "Crab Walk",
            "Plank"
    };
}
