package com.android.fitnessapplication;

public class ListOfWorkouts {
    static String[][] listOfWorkouts = {
            { "Explosive Chest",    //workout name
                "Chest",    // filter
                "3",        // # sets
                "16",       // number of indexes to loop, this number exercises times 2
                "Barbell Bench Press", "6-8", //this point down are the exercise name and reps
                "Dumbbell Bench Press", "10-12",
                "Chest Flies", "10-12",
                "Cable Flies", "10-12",
                "Chest Press", "10-12",
                "Incline Bench Press", "6-8",
                "Dips", "6-8",
                "Push-Ups", "15-20" },
            { "Pumped Up Shoulders",
                "Shoulders",
                "3",
                "14",
                "Military Press", "4-6",
                "Push Press", "AMRAP",              //1
                "Lateral Raises", "12-15",
                "Shrugs", "20",
                "Cable Extensions", "12",
                "Rear Delt Flies", "10-12",
                "Farmers Carry", "30" },        //sec
            { "Blasting Biceps",
                "Biceps",
                "4",
                "12",
                "Dumbbell Curl", "12",     //Each Arm  -- REPS EACH ARM
                "Hammer Curl", "12",       //Each Arm
                "Preacher Curl", "12",
                "Barbell Strict Curl", "8",
                "Chin-Ups", "AMRAP",                //1
                "Concentration Curl", "12" }, //Each Arm
            { "Tearing-Up Triceps",
                "Triceps",
                "4",
                "8",
                "Tricep Push-down", "12",
                "Dips", "AMRAP",                    //1
                "Skull-crushers", "10",
                "Push-Ups", "12" },
            { "Killer Core",
                "Abs & Obliques",
                "3",
                "14",
                "Sit-Ups", "12",
                "Crunches", "20",
                "Planks", "60",                 //sec
                "Hanging Leg Raises", "12",
                "Superman", "10",
                "Lumberjack Swings", "12", //Each Arm
                "Russian Twist", "20" },
            { "Light-Em-Up Legs",
                "Legs",
                "3",
                "16",
                "Back Squat", "8",
                "Front Squat", "8",
                "Leg Extensions", "12",
                "Calf Raises", "20",
                "Leg Press", "12",
                "Romanian Dead-lift", "10",
                "Lunges", "25",
                "Leg Curls", "12" },
            { "Bursting Back",
                "Back",
                "4",
                "14",
                "Barbell Dead-lift", "6",
                "Cleans", "4",
                "Lat Pull-down", "10-12",
                "Barbell Rows", "8",
                "Cable Rows", "12",
                "Pull-Ups", "AMRAP",                //1
                "T-bar Rows", "10" },
            { "Greedy Glutes",
                "Glutes",
                "3",
                "14",
                "Hip Thrusts", "8",
                "Back Squat", "6",
                "Trap-Bar Dead-lift", "6",
                "Kettle-bell Swing", "12",
                "Bulgarian Split Squat", "8",
                "Good Morning", "6",
                "Cable Kickback", "12" }
    };

    static String[][] exercises = {
            {"Back Squat", "back_squat"},
            {"Barbell Bench Press", "barbell_bench_press"},
            {"Barbell Dead-lift", "barbell_dead_lft"},
            {"Barbell Rows", "barbell_rows"},
            {"Barbell Strict Curl", "barbell_strict_curl"},
            {"Bulgarian Split Squat", "bulgarian_split_squat"},
            {"Cable Extensions", "cable_extensions"},
            {"Cable Flies", "cable_flies"},
            {"Cable Kickback", "cable_kickback"},
            {"Cable Rows", "cable_rows"},
            {"Calf Raises", "calf_raises"},
            {"Concentration Curl", "concentration_curl"},
            {"Chest Flies", "chest_flies"},
            {"Chest Press", "chest_press"},
            {"Chin-Ups", "chin_ups"},
            {"Cleans", "clean"},
            {"Crunches", "crunches"},
            {"Dips", "dips"},
            {"Dumbbell Bench Press", "dumbbell_bench_press"},
            {"Dumbbell Curl", "dumbell_curl"},
            {"Farmers Carry", "farmers_carry"},
            {"Front Squat", "front_squat"},
            {"Good Morning", "good_morning"},
            {"Hammer Curl", "hammer_curls"},
            {"Hanging Leg Raises", "hang_leg_raises"},
            {"Hip Thrusts", "hip_thrust"},
            {"Incline Bench Press", "incline_bench_press"},
            {"Kettle-bell Swing", "kettlebell_swings"},
            {"Lateral Raises", "lat_raises"},
            {"Lat Pull-down", "lat_pulldown"},
            {"Leg Curls", "leg_curl"},
            {"Leg Extensions", "leg_extension"},
            {"Leg Press", "leg_press"},
            {"Lumberjack Swings", "swings"},
            {"Lunges", "lunges"},
            {"Military Press", "military_press"},
            {"Preacher Curl", "preacher_curl"},
            {"Push Press", "push_press"},
            {"Push-Ups", "push_ups"},
            {"Pull-Ups", "pull_up"},
            {"Planks", "plank"},
            {"Rear Delt Flies", "rear_flies"},
            {"Romanian Dead-lift", "romanian_deadlift"},
            {"Russian Twist", "russian_twist"},
            {"Shrugs", "shrugs"},
            {"Sit-Ups", "situp"},
            {"Skull-crushers", "skull_crushers"},
            {"Superman", "superman"},
            {"T-bar Rows", "tbar_rows"},
            {"Trap-Bar Dead-lift", "trapbar_deadlift"},
            {"Tricep Push-down", ""},
    };
}
